# Generated by Django 5.2.5 on 2025-08-08 15:40

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('matricule', models.BigIntegerField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('etat', models.CharField(choices=[('a_venir', 'A venir'), ('en_cours', 'En cours'), ('terminee', 'Terminée')], default='a_venir', max_length=100)),
            ],
            options={
                'ordering': ['date_debut', 'date_fin'],
            },
        ),
        migrations.CreateModel(
            name='ProfilElecteur',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='electeur', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilSuperviseur',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='superviseur', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vote', models.DateField()),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election', to='vote.election')),
                ('candidat', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_candidat', to='vote.profilelecteur')),
                ('electeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electeur', to='vote.profilelecteur')),
            ],
        ),
        migrations.AddField(
            model_name='election',
            name='electeurs',
            field=models.ManyToManyField(through='vote.Vote', through_fields=('election', 'electeur'), to='vote.profilelecteur'),
        ),
        migrations.AddField(
            model_name='election',
            name='superviseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superviseur', to='vote.profilsuperviseur'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('electeur', 'election'), name='unique_person_group'),
        ),
    ]
