# Generated by Django 5.2.5 on 2025-08-08 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_candidature', models.DateField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_person_group',
        ),
        migrations.AlterField(
            model_name='vote',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_vote', to='vote.election'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('electeur', 'election'), name='unique_vote_par_election'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='candidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidat', to='vote.profilelecteur'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_candidature', to='vote.election'),
        ),
        migrations.AddField(
            model_name='election',
            name='candidats',
            field=models.ManyToManyField(related_name='candidats', through='vote.Candidature', to='vote.profilelecteur'),
        ),
        migrations.AddConstraint(
            model_name='candidature',
            constraint=models.UniqueConstraint(fields=('candidat', 'election'), name='unique_candidature_par_election'),
        ),
    ]
