<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-09-16 01:14
=======
# Generated by Django 5.2.5 on 2025-09-15 14:32
>>>>>>> e0320a1d59463af1ed94c22385985d9958237771

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-date_candidature', 'election_id']},
        ),
        migrations.AddField(
            model_name='candidate',
            name='description',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_accepted',
            field=models.CharField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='reject_message',
            field=models.CharField(blank=True),
        ),
<<<<<<< HEAD
=======
        migrations.AddField(
            model_name='customuser',
            name='token',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='token_expiration',
            field=models.DateTimeField(null=True),
        ),
>>>>>>> e0320a1d59463af1ed94c22385985d9958237771
        migrations.AlterField(
            model_name='candidate',
            name='date_candidature',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
<<<<<<< HEAD
            field=models.DateField(default=datetime.date(2025, 9, 16)),
=======
            field=models.DateField(default=datetime.date(2025, 9, 15)),
>>>>>>> e0320a1d59463af1ed94c22385985d9958237771
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_candidate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_elector',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
<<<<<<< HEAD
=======
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, null=True, verbose_name='password'),
        ),
        migrations.AlterField(
>>>>>>> e0320a1d59463af1ed94c22385985d9958237771
            model_name='vote',
            name='date_vote',
            field=models.DateTimeField(),
        ),
    ]
