# Generated by Django 5.2.5 on 2025-09-16 01:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-date_candidature', 'election_id']},
        ),
        migrations.AddField(
            model_name='candidate',
            name='description',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_accepted',
            field=models.CharField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='reject_message',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='date_candidature',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(default=datetime.date(2025, 9, 16)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_candidate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_elector',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='date_vote',
            field=models.DateTimeField(),
        ),
    ]
