# Generated by Django 5.2.5 on 2025-09-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_alter_candidate_options_candidate_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='descripton',
            field=models.CharField(default='Une description pour cette election', max_length=1000),
            preserve_default=False,
        ),
    ]
