# Generated by Django 5.2.5 on 2025-09-15 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_election_descripton'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='descripton',
            new_name='description',
        ),
    ]
